<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>com.ozonehis.odoo</groupId>
    <artifactId>odoo-sso-user-roles</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>Odoo SSO User Roles</name>
    <description>
        Odoo add-on to assign the roles defined in the authentication provider to a user as groups upon login
    </description>

    <scm>
        <connection>scm:git:git@github.com:ozone-his/odoo-sso-user-roles.git</connection>
        <developerConnection>scm:git:git@github.com:ozone-his/odoo-sso-user-roles.git</developerConnection>
        <url>https://github.com/ozone-his/odoo-sso-user-roles.git</url>
        <tag>HEAD</tag>
    </scm>

    <organization>
        <name>Ozone HIS</name>
        <url>http://www.ozone-his.com</url>
    </organization>
    <developers>
        <developer>
            <name>Mekom Solutions</name>
            <url>http://www.mekomsolutions.com</url>
        </developer>
    </developers>

    <properties>
        <odooVersion>17.0</odooVersion>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.3.1</version>
                <executions>
                    <execution>
                        <id>Substitute addon version with Maven properties</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>
                                ${project.build.directory}/${project.artifactId}-${project.version}/</outputDirectory>
                            <overwrite>true</overwrite>
                            <resources>
                                <resource>
                                    <directory>${project.basedir}/</directory>
                                    <includes>
                                        <include>*.py</include>
                                        <include>models/*.py</include>
                                    </includes>
                                    <filtering>true</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.6.0</version>
                <executions>
                    <execution>
                        <id>capture-timestamp</id>
                        <goals>
                            <goal>timestamp-property</goal>
                        </goals>
                        <configuration>
                            <name>version.timestamp</name>
                            <pattern>yyyyMMddHHmmssSSS</pattern>
                        </configuration>
                    </execution>
                    <execution>
                        <goals>
                            <goal>regex-property</goal>
                        </goals>
                        <configuration>
                            <name>addonVersion</name>
                            <value>${project.version}</value>
                            <regex>-SNAPSHOT</regex>
                            <replacement>${version.timestamp}</replacement>
                            <failIfNoMatch>false</failIfNoMatch>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.7.1</version>
                <executions>
                    <execution>
                        <id>package-odoo-addon</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <appendAssemblyId>false</appendAssemblyId>
                            <descriptors>
                                <descriptor>assembly.xml</descriptor>
                            </descriptors>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <distributionManagement>
        <repository>
            <id>mks-nexus-public-releases</id>
            <name>Mekom Solutions Nexus repo for releases</name>
            <url>https://nexus.mekomsolutions.net/repository/maven-releases</url>
        </repository>
        <snapshotRepository>
            <id>mks-nexus-public-snapshots</id>
            <name>Mekom Solutions Nexus repo for snapshots</name>
            <url>https://nexus.mekomsolutions.net/repository/maven-snapshots</url>
        </snapshotRepository>
    </distributionManagement>
</project>